require("user.plugins.launch")

require("user.options")
require("user.keymaps")

--require("user.autocommands")

-- coding
spec("user.plugins.autopairs")
spec("user.plugins.ts-comments")
spec("user.plugins.gitsigns")
spec("user.plugins.blink")
spec("user.plugins.dap")
spec("user.plugins.renamer")

--UI
spec("user.plugins.colorscheme")
spec("user.plugins.nvimtree")
spec("user.plugins.lualine")
spec("user.plugins.navic")
spec("user.plugins.breadcrums")

-- Editor
spec("user.plugins.flash")
spec("user.plugins.whichkey")
spec("user.plugins.todo-comments")
spec("user.plugins.telescope")
spec("user.plugins.dial")
spec("user.plugins.harpoon")
spec("user.plugins.treesitter")
spec("user.plugins.nvim-ts-autotags")
spec("user.plugins.snacks")
spec("user.plugins.illuminate")

-- LSP and support
spec("user.plugins.lsp.lsp-config")
spec("user.plugins.lsp.mason")
spec("user.plugins.none-ls")

--spec("user.plugins.dressing")
--spec("user.plugins.devicons")
--spec("user.plugins.cmp")
--spec("user.plugins.mason")
--spec("user.plugins.schemastore")
--spec("user.plugins.lsp_lines")
--spec("user.plugins.comment")
--spec("user.plugins.diffview")
--spec("user.plugins.indentline")
--spec("user.plugins.alpha")
--spec("user.plugins.project")
--spec("user.plugins.toggleterm")
--spec("user.plugins.bufdelete")
--spec("user.plugins.notify")
--spec("user.plugins.cybu")
--spec("user.plugins.fidgit")
--spec("user.plugins.neoscroll")
--spec("user.plugins.nvim-ufo")
--spec("user.plugins.fugitive")
--spec("user.plugins.colorizer")
--spec("user.plugins.hop")
--spec("user.plugins.dap")
--spec("user.plugins.rust-tools")
--spec("user.plugins.crates")

require("user.lazy")
