require "user.options"
require "user.keymaps"
require "user.autocommands"
require "user.plugin"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.nvim-web-devicons"
require "user.bufferline"
-- require "user.lualine"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
-- require "user.indentline"
require "user.alpha"
require "user.whichkey"
-- require "user.colorized"
-- require "user.renamer"
-- require "user.symbol-outline"
-- require "user.matchup"
-- require "user.git-blame"
-- require "user.compitest"
-- require "user.vimspector"
-- require "user.todo-comments"
-- require "user.asyncrun"
-- require "user.auto-session"
-- require "user.session-lens"
-- require "user.numb"
-- require "user.bookmark"
-- require "user.dressing"
-- require "user.illuminate"
-- require "user.hop"
-- require "user.surround"
require "user.notify"
-- require "user.fidget"
-- require "user.browse"
-- require "user.jabs"

-- require "user.cybu"
-- require "user.leetcode"
-- require "user.twilight"
-- require "user.dap"
-- require "user.functions"
-- require "user.session-manager"
-- require "user.gist"
-- require "user.ts-context"
-- require "user.quickscope"

if (vim.g.vscode) then require "user.vscode" end
